### ISSUE TITLE
Can't use prebuilt binaries

### ISSUE THREAD

**Issue by rupertnash** [eWaterCycle/setup-singularity#1]
Hi @sverhoeven -

Thanks for this nice tool. I'm trying to move the cwltool (https://github.com/common-workflow-language/cwltool) to use GitHub Actions for its CI and we need Singularity for some tests.

This works, but building from source is a bit slow. I believe 3.6.4 is available on ubuntu 20.04 (it's in https://github.com/eWaterCycle/singularity-versions/blob/main/versions-manifest.json) so I think this *should* work, but it doesn't.

See e.g. https://github.com/rupertnash/cwltool/runs/2034402926?check_suite_focus=true#step:3:206

Any help debugging gratefully received. Thanks

https://github.com/rupertnash/cwltool/runs/2034402926?check_suite_focus=true#step:3:206

**Comment by sverhoeven** [comment]
I am able to reproduce in https://github.com/eWaterCycle/grpc4bmi/runs/2039491900?check_suite_focus=true , it compiles for 2m14s instead of using binary build.

**Comment by sverhoeven** [comment]
In PR #2 was able to fix it, see https://github.com/eWaterCycle/grpc4bmi/runs/2039754613?check_suite_focus=true 

Can you test with?
```
 - name: Setup Singularity
      uses: eWaterCycle/setup-singularity@v6
      with:
        singularity-version: 3.6.4
```

**Comment by rupertnash** [comment]
Stefan - thanks for this super speedy fix! This works now.
